[package]
name = "clixon-rustapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.23"
regex = "1.11.1"
xmltree = "0.11.0"

[[bin]]
name = "clixon-rustapi"
path = "src/main.rs"
